routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'ProfileController@index')->name('profile');
Route::post('/profile/{id}/update', 'ProfileController@update')->name('profile.update');

Route::prefix('/map')->middleware('auth')->group(function() {
    Route::get('/', 'HomeController@index');

    Route::resources(['users' => 'UserController', 'marks' => 'MarkController']);
    Route::get('/getmarks', 'MarkController@getmarks');
});

//chat
Route::post('messages', 'ChatController@getmessage');
Route::get('getuser', 'ChatController@getuser');
Route::get('getuser', 'ChatController@getuser');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|email',
            'password' =>'required'
        ]);
        $email =$request->input('email');
        if (User::where('email', $email)->first()){
            return redirect()->back()->with('mess', 'Пользователь с такой почтой уже зарегистрирован на сайте');
        } else {
            $user = new User();
            $user->email= $email;
            $user->name = $request->input('name');
            $user->password = bcrypt($request->input("password"));
            $user->save();
            return redirect('map/users')->with('mess', 'Новый пользователь успешно создан!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('users.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'email' => 'required|email',
            'password' =>'required'
        ]);
        User::where('id', $id)->update([
            'email' => $request->input('email'),
            'name' => $request->input('name'),
            'password' => bcrypt($request->input('password')),
        ]);
        return redirect('map/users')->with('mess', 'Пользователь успешно изменен!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return redirect('map/users');
    }
}

resources/views/users/form.blade.php
@extends('layouts.main')
@section('content')
    <div class="container">


            @if(isset($user))
                <h1>Изменить пользователя</h1>
            @else
                <h1>Добавить пользователя</h1>
            @endif
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

            <form action="{{isset($user) ? route('users.update', $user->id): route('users.store')}}" method="post" enctype = 'multipart/form-data' >
                @csrf
                @if(isset($user))
                    @method('PUT')
                @endif
                @if(session('mess'))
                    <p class="text-danger">
                        {{session('mess')}}
                    </p>
                @endif
                <div class="form-group mt-3">
                    <label for="">Имя:</label><br>
                    <input class="form-control" name='name' type="text" value="{{isset($user) ? $user->name : ''}}" >
                </div>


                <div class="form-group mt-3">
                    <label for=""> Почта:</label><br>
                    <input class="form-control" name='email'  type="text" value ="{{isset($user) ? $user->email : ''}}">
                </div>
                <div class="form-group mt-3">
                    <label for=""> Пароль:</label><br>
                    <input class="form-control" name='password'  type="text" value="">
                </div>

                @if(isset($user))
                    <input type="submit" class="mt-3 btn btn-success" value="Изменить">
                @else
                    <input type="submit" class="mt-3 btn btn-success" value="Добавить ">
                @endif

            </form>

    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.main')
@section('content')
<div class="container">
    <h1>Пользователи</h1>

    <a href="{{route('users.create')}}" class="btn mt-3 mb-3 btn-success">Добавить пользователя</a>

    <br>
    @if(session('mess'))
        <p class="text-success">
            {{session('mess')}}
        </p>
    @endif
    @if(session('error'))
        <p class="text-success">
            {{session('error')}}
        </p>
    @endif

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>Имя </th>
            <th>E-mail</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{$user->name}}</td>

                <td>{{$user->email}} </td>

                <td>
                    <a href="{{route('users.edit', $user->id)}}"  class="btn mb-2 btn-info">Изменить</a>
                    <form action="{{route('users.destroy', $user->id)}}" method="post">
                        @csrf
                        {{method_field('DELETE')}}
                        <input type="submit" class="btn btn-danger" value ='Удалить'/>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>

    </table>
</div>
    @endsection